version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ~/.log/nginx:/var/log/nginx
    links:
      - php

  php:
    build: .
    container_name: ig_todo
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysqldb
  myadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_CONNECTION}
    restart: always
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: ${DB_CONNECTION}
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - ~/.mysql_data_57/:/var/lib/mysql
